### ISSUE TITLE
Could not find KfW installation.

### ISSUE THREAD

**Issue by achapkowski** [pythongssapi/requests-gssapi#27]
On windows 10 with python 3.6.10, I get the following error:

```
>>> import requests_gssapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\requests_gssapi\__init__.py", line 17, in <module>
    from .gssapi_ import HTTPSPNEGOAuth, REQUIRED, OPTIONAL, DISABLED  # noqa
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\requests_gssapi\gssapi_.py", line 6, in <module>
    import gssapi
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\gssapi\__init__.py", line 29, in <module>
    import gssapi._win_config  # noqa
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\gssapi\_win_config.py", line 74, in <module>
    configure_windows()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\gssapi\_win_config.py", line 70, in configure_windows
    error_not_found()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\emptypy36\lib\site-packages\gssapi\_win_config.py", line 38, in error_not_found
    % (KFW_DL, KFW_BIN)
OSError: Could not find KfW installation. Please download and install the 64bit Kerberos for Windows MSI from https://web.mit.edu/KERBEROS/dist and ensure the 'bin' folder (C:\Program Files\MIT\Kerberos\bin) is in your PATH.
```

Any ideas?

**Comment by frozencemetery** [comment]
Well, let's start super basic.  Did you install KfW?  Where is it?

**Comment by frozencemetery** [comment]
Closing due to lack of response.
