### ISSUE TITLE
PIP install: /bin/sh: krb5-config: command not found

### ISSUE THREAD

**Issue by nmz787** [pythongssapi/requests-gssapi#43]
just tried installing from pypi, and got that error.

```
You should consider upgrading via the 'pip install --upgrade pip' command.
myServer> python3.7.4  -m pip install --user requests-gssapi
Collecting requests-gssapi
  Using cached https://files.pythonhosted.org/packages/91/d8/67b9ad0c416cdc020f6685fb83bcc7a2e2de77864ab0805ca04cee21b55a/requests-gssapi-1.2.3.tar.gz
Requirement already satisfied: requests>=1.1.0 in /home/nmz787/.local/lib/python3.7/site-packages (from requests-gssapi) (2.26.0)
Collecting gssapi (from requests-gssapi)
  Using cached https://files.pythonhosted.org/packages/e4/4d/03fcc6a2d052920336069df97866d7b506556ed9f3a5ee2ca1e0cbad45d4/gssapi-1.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: krb5-config: command not found
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6cpfplub/gssapi/setup.py", line 128, in <module>
        link_args = shlex.split(get_output(f"{kc} --libs gssapi"))
      File "/tmp/pip-install-6cpfplub/gssapi/setup.py", line 41, in get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/bin/python3/3.7.4/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/bin/python3/3.7.4/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6cpfplub/gssapi/
```

**Comment by jborean93** [comment]
Trying to install the [gssapi](https://pypi.org/project/gssapi/) is failing because it cannot find the `krb5-config` binary on your system to get the GSSAPI installation details on your host. Make sure you have that installed and is on the `PATH` for Python to use when installing.

**Comment by nmz787** [comment]
moved to a system with `krb5-config` installed
